
export const Videos = [
  {
    title: "JIGRA - OFFICIAL TEASER TRAILER  | Ulti Ginti Shuru | Alia Bhatt | Vedang Raina | Vasan Bala| 11 Oct",
    thumbnil: "/photo1.jpg",
    logo: "/logo1.jpg",
    description: "Dharma Production",
    viewCount: "37M views",
    timeStamp: "7 days ago",
  },
  {
    title: "Aaj Ki Raat : Remix | Tamannaah Bhatia | Sachin-Jigar | Stree 2 | Sidha ladka |  Madhubanti Bagchi",
    thumbnil: "/photo2.jpg",
    logo: "/logo2.jpg",
    description: "Antique Melodies",
    viewCount: "5.3M views",
    timeStamp: "1 month ago",
  },
  {
    title: "The Great Indian Kapil Show: Season 2 | Official Trailer | 21st Sept, Saturdays 8pm | Netflix",
    thumbnil: "/photo3.jpg",
    logo: "/logo3.jpg",
    description: "Netflix India",
    viewCount: "12M views",
    timeStamp: "1 day ago",
  },
  {
    title: "VICKY VIDYA KA WOH WALA VIDEO - TRAILER | RAJKUMMAR RAO, TRIPTII DIMRI | RAAJ S | BHUSHAN K | 11 OCT",
    thumbnil: "/photo4.jpg",
    logo: "/logo4.jpg",
    description: "T-Series",
    viewCount: "23M views",
    timeStamp: "3 days ago",
  },
  {
    title: "JIGRA - OFFICIAL TEASER TRAILER  | Ulti Ginti Shuru | Alia Bhatt | Vedang Raina | Vasan Bala| 11 Oct",
    thumbnil: "/photo1.jpg",
    logo: "/logo1.jpg",
    description: "Dharma Production",
    viewCount: "37M views",
    timeStamp: "7 days ago",
  },
  {
    title: "Aaj Ki Raat : Remix | Tamannaah Bhatia | Sachin-Jigar | Stree 2 | Sidha ladka |  Madhubanti Bagchi",
    thumbnil: "/photo2.jpg",
    logo: "/logo2.jpg",
    description: "Antique Melodies",
    viewCount: "5.3M views",
    timeStamp: "1 month ago",
  },
  {
    title: "The Great Indian Kapil Show: Season 2 | Official Trailer | 21st Sept, Saturdays 8pm | Netflix",
    thumbnil: "/photo3.jpg",
    logo: "/logo3.jpg",
    description: "Netflix India",
    viewCount: "12M views",
    timeStamp: "1 day ago",
  },
  {
    title: "VICKY VIDYA KA WOH WALA VIDEO - TRAILER | RAJKUMMAR RAO, TRIPTII DIMRI | RAAJ S | BHUSHAN K | 11 OCT",
    thumbnil: "/photo4.jpg",
    logo: "/logo4.jpg",
    description: "T-Series",
    viewCount: "23M views",
    timeStamp: "3 days ago",
  },
  {
    title: "JIGRA - OFFICIAL TEASER TRAILER  | Ulti Ginti Shuru | Alia Bhatt | Vedang Raina | Vasan Bala| 11 Oct",
    thumbnil: "/photo1.jpg",
    logo: "/logo1.jpg",
    description: "Dharma Production",
    viewCount: "37M views",
    timeStamp: "7 days ago",
  },
  {
    title: "Aaj Ki Raat : Remix | Tamannaah Bhatia | Sachin-Jigar | Stree 2 | Sidha ladka |  Madhubanti Bagchi",
    thumbnil: "/photo2.jpg",
    logo: "/logo2.jpg",
    description: "Antique Melodies",
    viewCount: "5.3M views",
    timeStamp: "1 month ago",
  },
  {
    title: "The Great Indian Kapil Show: Season 2 | Official Trailer | 21st Sept, Saturdays 8pm | Netflix",
    thumbnil: "/photo3.jpg",
    logo: "/logo3.jpg",
    description: "Netflix India",
    viewCount: "12M views",
    timeStamp: "1 day ago",
  },
  {
    title: "VICKY VIDYA KA WOH WALA VIDEO - TRAILER | RAJKUMMAR RAO, TRIPTII DIMRI | RAAJ S | BHUSHAN K | 11 OCT",
    thumbnil: "/photo4.jpg",
    logo: "/logo4.jpg",
    description: "T-Series",
    viewCount: "23M views",
    timeStamp: "3 days ago",
  },
  {
    title: "JIGRA - OFFICIAL TEASER TRAILER  | Ulti Ginti Shuru | Alia Bhatt | Vedang Raina | Vasan Bala| 11 Oct",
    thumbnil: "/photo1.jpg",
    logo: "/logo1.jpg",
    description: "Dharma Production",
    viewCount: "37M views",
    timeStamp: "7 days ago",
  },
  {
    title: "Aaj Ki Raat : Remix | Tamannaah Bhatia | Sachin-Jigar | Stree 2 | Sidha ladka |  Madhubanti Bagchi",
    thumbnil: "/photo2.jpg",
    logo: "/logo2.jpg",
    description: "Antique Melodies",
    viewCount: "5.3M views",
    timeStamp: "1 month ago",
  },
  {
    title: "The Great Indian Kapil Show: Season 2 | Official Trailer | 21st Sept, Saturdays 8pm | Netflix",
    thumbnil: "/photo3.jpg",
    logo: "/logo3.jpg",
    description: "Netflix India",
    viewCount: "12M views",
    timeStamp: "1 day ago",
  },
  {
    title: "VICKY VIDYA KA WOH WALA VIDEO - TRAILER | RAJKUMMAR RAO, TRIPTII DIMRI | RAAJ S | BHUSHAN K | 11 OCT",
    thumbnil: "/photo4.jpg",
    logo: "/logo4.jpg",
    description: "T-Series",
    viewCount: "23M views",
    timeStamp: "3 days ago",
  },

]
